USE model;


SELECT DB_NAME() AS BaseDeDatosActual;


CREATE TABLE CUSTOMER (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DNI CHAR(8) NOT NULL,
    CELLPHONE CHAR(9) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    STATE CHAR(1) NOT NULL,
    CREATED_AT DATETIME NULL DEFAULT GETDATE(),              -- Fecha de creación
    UPDATED_AT DATETIME NULL,                                -- Fecha de última actualización
    DELETED_AT DATETIME NULL,                                -- Fecha de eliminación lógica
    RESTORED_AT DATETIME NULL                                -- Fecha de restauración 
);

CREATE TABLE PRODUCT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(150) NOT NULL,
    PURCHASE_PRICE DECIMAL(5,2) NOT NULL,
    SALE_PRICE DECIMAL(5,2) NOT NULL,
    STOCK INT NOT NULL,
    STATE CHAR(1) NOT NULL
);


CREATE TABLE SALE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    SALE_DATE DATETIME DEFAULT GETDATE() NOT NULL,
    TOTAL DECIMAL(5,2) NOT NULL,
    STATE CHAR(1) NOT NULL,
    CONSTRAINT FK_SALE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);


CREATE TABLE SALE_DETAIL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SALE_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    SUBTOTAL DECIMAL(5,2) NOT NULL,
    STATE CHAR(1) NOT NULL,
    CONSTRAINT FK_SALE_DETAIL_SALE FOREIGN KEY (SALE_ID) REFERENCES SALE(ID),
    CONSTRAINT FK_SALE_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);


INSERT INTO CUSTOMER 
(DNI, CELLPHONE, FIRST_NAME, LAST_NAME, STATE)
VALUES 
('74564578', '987654321', 'Juan', 'Sanchez', 'A'),
('87654321', '912345678', 'María', 'Lopez', 'A'),
('45678912', '999888777', 'Carlos', 'Ramirez', 'A');


INSERT INTO PRODUCT 
(NAME, DESCRIPTION, PURCHASE_PRICE, SALE_PRICE, STOCK, STATE) 
VALUES 
('Galleta', 'De chocolate', 2.50, 3.00, 10, 'A'),
('Refresco', 'Bebida gaseosa de 500ml', 1.20, 2.00, 25, 'A'),
('Pan', 'Pan integral 100g', 0.80, 1.50, 15, 'A');


SELECT * FROM CUSTOMER;

SELECT * FROM PRODUCT;

SELECT * FROM SALE;

SELECT * FROM SALE_DETAIL;


# JSON en POSTMAN para la creación de una VENTA  con su DETALLE DE VENTA
{
  "customerId": 1,
  "products": [
    { "productId": 1, "quantity": 3 },
    { "productId": 2, "quantity": 4 }
  ]
}


DROP TABLE CUSTOMER;

DROP TABLE PRODUCT;

DROP TABLE SALE;

DROP TABLE SALE_DETAIL;
