# docker-compose -f docker-compose-be.yml up -d
# docker-compose -f docker-compose-be.yml down
version: '3'

services:
  backend:
    build: 
      context: ..
      dockerfile: dockerfile
    image: axelhuapaya/springboot-sqlserver:1.0 
    container_name: springboot-sqlserver
    restart: on-failure
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - SERVER_URL=http://localhost:5001
      - DATABASE_URL=jdbc:sqlserver://sql-server:1433;databaseName=agro_pacayales;encrypt=true;trustServerCertificate=true
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=Admin12345
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
    networks:
      - my-network

# CONSUMIR UNA RED EXISTENTE CREADA POR OTRO COMPOSE
networks:
  my-network:
    external: true   # usa la red creada por el compose de la base de datos
    
